import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/Layout/Footer"
import Navbar from "../components/Layout/Navbar"
import { UserProvider } from "../context/UserContext"
import { Toaster } from 'react-hot-toast';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Navbar />
          <main>
            {children}
            <Toaster position="top-right" reverseOrder={false} />
          </main>
          <footer>
            <Footer />
          </footer>
        </body>
      </UserProvider>
    </html >
  );
}
